# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:	true

# Permalinks
permalink:	/:title

# Setup
title:		Otevřeme Radotín
tagline:	'blog'
description:	"Volební sdružení Pirátů, KDU-ČSL a nezávislých kandidátů do zastupitelstva Městské části Praha 16"
url:		http://www.otevremeradotin.cz

author:
  name:		'Jakub Michálek'
  url:		https://www.pirati.cz/lide/jakub_michalek

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	facebook
    url:	https://facebook.com/otevremeradotin
    desc:	Sledujte nás na facebooku

  - icon:	github
    url:	https://github.com/jmichalek/otevremeradotin
    desc:	Založte novou větev na githubu

  - icon:	feed
    url:	http://www.otevremeradotin.cz/atom.xml
    desc:	Odběr aktualit
    
menu:
  - title:	Úvod
    url:	/
    
  - title:	Program
    url:	/program

    
copyright:
  author:	Jakub Michálek
  type_url:		/cited
  type_title:	Použité materiály
